### ISSUE TITLE
Error on  npm run build

### ISSUE THREAD

**Issue by Stunkamator** [storyblok/nuxtjs#1]
Hello,

after downloading and doing some simple changes on vue html, i wanted to build the application, but there seems to be a problem with uglify js.

ERROR in app.77522ed573da21396bbc.js from UglifyJs
Unexpected token: name (memory) [./node_modules/storyblok-js-client/index.js:6,0                                                                                                                                                                                               ][app.77522ed573da21396bbc.js:9562,4]

I am using npm version 5.7.1 and Node Version 7.7.2

I did not do any changes on the package.json.

Any suggestion on how to fix the issue or at least get rid of uglify.js?

**Comment by DominikAngerer** [comment]
Hey there. We've not yet run into this issue before. I'll make some test and try to reproduce it to help you go forward on this. 

Could you try Node Version 8+ and let me know if the issue persists?

Best,
Dominik

BTW: updated example: https://github.com/storyblok/nuxtwebsite

**Comment by Stunkamator** [comment]
Hi, I updated to node 8.11.1, but the error is still there on  `npm run build` and `npm run generate`

**Comment by Stunkamator** [comment]
Hi, i found the problem, `npm install storyblok-js-client --save` fixed the issue.
The package was missing in package.json

**Comment by DominikAngerer** [comment]
Thanks for that. I've had a look at the dependency tree and it should be contained in `storyblok-nuxt` itself. I'll do some further tests on this and add, by now, add it to the package.json. Thanks! 👍

**Comment by DominikAngerer** [comment]
https://github.com/storyblok/nuxtjs/commit/603a207a63ca08086869c762a6dd318bb84bf81f
